# practice NumPy

numpy is the core library for scientific and numerical computing in python

it provide high performance multidimensional array object and tools for working with arrays

Numpy main object is the multidimentional arrays

it is a table of element all of the same type,indexed by  a tuple of positive integers

in Numpy,dimensions are called axes

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) #1D
print(a)

[1 2 3]


In [3]:
b = np.array([[4,5,6],[7,8,9]]) #2D
print(b)

[[4 5 6]
 [7 8 9]]


In [4]:
#get dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#get shape
a.shape


(3,)

In [7]:
b.shape

(2, 3)

In [8]:
#get type
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('int32')

In [10]:
#get size 8+8+8+8 int32
a.itemsize


4

In [11]:
b.itemsize

4

In [12]:
#get array size
a.size

3

In [13]:
b.size

6

In [14]:
#get total size
a.nbytes

12

In [15]:
b.nbytes

24

# Accessing/Changing specific elements,rows,columns,etc

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
a.shape

(2, 7)

In [18]:
#get a specific element
a[1,5]

13

In [19]:
a[1,-2]

13

In [20]:
#getting a specific column
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#get a specific column
a[:,5]

array([ 6, 13])

In [22]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:7:2]

array([2, 4, 6])

In [23]:
a[0,1:-1:2]

array([2, 4, 6])

In [24]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [26]:
a[:,2] = [1,4]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  4 11 12 20 14]]


# 3D example

In [27]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
b[0,1,1]

4

In [29]:
b[1,1,1]

8

In [30]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [31]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [32]:
#replace
b[:,1,:] = [[9,9],[8,7]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 7]]]


# Initialization different Type of Array

In [33]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.zeros((3,2,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [42]:
#all 1s matrix
np.ones((4,2,2),dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
#all other nunber
np.full((2,2),99,dtype ='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [45]:
#All othe full like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
#random decimal number
np.random.rand(4,2)

array([[0.60724887, 0.39835939],
       [0.77019744, 0.52758685],
       [0.94098967, 0.71778341],
       [0.06557688, 0.64857273]])

In [47]:
np.random.rand(4,2,3)

array([[[0.05030987, 0.5810904 , 0.30999429],
        [0.03840079, 0.24900201, 0.24897808]],

       [[0.99446005, 0.97916631, 0.7360022 ],
        [0.47382229, 0.09490685, 0.67415102]],

       [[0.03553521, 0.64953761, 0.48715613],
        [0.17631547, 0.9009783 , 0.61097033]],

       [[0.15966234, 0.55434291, 0.25852667],
        [0.84022948, 0.41858187, 0.55045828]]])

In [49]:
#random integer value
np.random.randint(7,size = (3,3))

array([[2, 3, 0],
       [6, 1, 2],
       [0, 1, 2]])

In [52]:
np.random.randint(3,7,size = (3,3)) #in between 3,7

array([[4, 4, 3],
       [6, 5, 6],
       [3, 5, 4]])

In [53]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
#Repeat an array
arr = np.array([[1,2,3,4]])
r = np.repeat(arr,3)
print(r)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [60]:
arr = np.array([[1,2,3,4]])
r = np.repeat(arr,3,axis = 0)
print(r)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [62]:
out = np.ones((5,5))
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
 z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [67]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [75]:
out = np.ones((5,5))
print(out)
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)
out[1:4,1:4] = z
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [77]:
#copy array
a = np.array([1,2,3])
b = a.copy()
print(a)
b[0] = 23
print(b)



[1 2 3]
[23  2  3]


# mathematics


In [78]:
a  = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [79]:
a+2

array([3, 4, 5, 6])

In [80]:
a-2

array([-1,  0,  1,  2])

In [81]:
a*3

array([ 3,  6,  9, 12])

In [82]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [83]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [84]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [85]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra


In [90]:
a = np.full((2,3),2)
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[2 2]
 [2 2]
 [2 2]]


array([[12, 12],
       [12, 12]])

In [92]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
#we can also de 
#(https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)


#determinant
#Traces
#singular vector decomposition
#Eigenvalues
#matrix Norm
#Inverse
#Etc


# Statistics


In [94]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.min(stats)

1

In [97]:
np.max(stats)

6

In [98]:
np.sum(stats)

21

In [99]:
np.sum(stats,axis = 0)

array([5, 7, 9])

# Reorganizing arrays

In [100]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [101]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [106]:
#Horizontal stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,5))
np.hstack((h1,h2,h1))
    

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1.]])

# Miscellaneous things

In [ ]:
#load data from file


In [ ]:
filedat = np.genfromtxt('data.txt',delimites = ',') #file data in the form of matrix
filedata = filedata.astype('int32')
print(filedata)

In [ ]:
#boolean masking and indexing

In [ ]:
filedata[filedata>50]

In [ ]:
np.any(filedata>50,axis = 0)

In [ ]:
((filedata > 50 & filedata < 100))